"""duplicate failure records can be retired

Revision ID: 9bec660e0ec5
Revises: d3643d752b53
Create Date: 2026-09-08 10:45:40.841590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Migrations reference the portable column types by their full path (Part B §6, §43).
import civitas.persistence.types


# revision identifiers, used by Alembic.
revision: str = '9bec660e0ec5'
down_revision: Union[str, Sequence[str], None] = 'd3643d752b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duplicate_failure_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retired_at', civitas.persistence.types.UTCDateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_duplicate_failure_records_retired_at'), ['retired_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duplicate_failure_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duplicate_failure_records_retired_at'))
        batch_op.drop_column('retired_at')

    # ### end Alembic commands ###
